/**
 * CreateTeamDialog - Modal for creating a new Claude Agent Team.
 * Fields: name, description, teammates with per-teammate config.
 */
import { useState, useCallback } from 'react';
import { X, Users, Plus, Minus, Play, User } from 'lucide-react';
import { useClaudeTeamsStore } from '../../stores/claude-teams-store';

interface TeammateConfig {
  name: string;
  prompt: string;
  model: string;
  planModeRequired: boolean;
}

const DEFAULT_TEAMMATE: TeammateConfig = {
  name: '',
  prompt: '',
  model: 'claude-sonnet-4-5-20250929',
  planModeRequired: false,
};

const MODEL_OPTIONS = [
  { value: 'claude-opus-4-6', label: 'Opus 4.6' },
  { value: 'claude-sonnet-4-5-20250929', label: 'Sonnet 4.5' },
  { value: 'claude-haiku-4-5-20251001', label: 'Haiku 4.5' },
];

interface CreateTeamDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CreateTeamDialog({ isOpen, onClose }: CreateTeamDialogProps) {
  const createTeam = useClaudeTeamsStore((s) => s.createTeam);

  const [description, setDescription] = useState('');
  const [teammates, setTeammates] = useState<TeammateConfig[]>([{ ...DEFAULT_TEAMMATE }]);
  const [isCreating, setIsCreating] = useState(false);

  if (!isOpen) return null;

  const addTeammate = () => {
    if (teammates.length >= 6) return;
    setTeammates([...teammates, { ...DEFAULT_TEAMMATE }]);
  };

  const removeTeammate = (index: number) => {
    if (teammates.length <= 1) return;
    setTeammates(teammates.filter((_, i) => i !== index));
  };

  const updateTeammate = (index: number, updates: Partial<TeammateConfig>) => {
    setTeammates(
      teammates.map((t, i) => (i === index ? { ...t, ...updates } : t))
    );
  };

  const handleCreate = async () => {
    if (!description.trim()) return;

    setIsCreating(true);
    try {
      const success = await createTeam({
        name: '', // Name is auto-generated by Claude CLI
        description: description.trim(),
        teammates: teammates
          .filter((t) => t.name.trim() || t.prompt.trim())
          .map((t) => ({
            name: t.name.trim(),
            prompt: t.prompt.trim(),
            model: t.model,
            planModeRequired: t.planModeRequired,
          })),
      });

      if (success) {
        // Reset form
        setDescription('');
        setTeammates([{ ...DEFAULT_TEAMMATE }]);
        onClose();
      }
    } catch (err) {
      console.error('[CreateTeamDialog] create error:', err);
    } finally {
      setIsCreating(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Dialog */}
      <div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-lg mx-4 max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border flex-shrink-0">
          <div className="flex items-center gap-3">
            <Users className="w-5 h-5 text-primary" />
            <h2 className="text-lg font-semibold">Create Team</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-secondary transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 overflow-y-auto flex-1">
          {/* Task Description */}
          <div>
            <label className="block text-sm font-medium text-muted-foreground mb-2">
              Task Description
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What should the team work on?"
              rows={3}
              className="w-full px-4 py-3 rounded-lg bg-secondary border border-border focus:border-primary focus:outline-none resize-none text-sm"
            />
          </div>

          {/* Teammates */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-muted-foreground">
                Teammates ({teammates.length}/6)
              </label>
              <button
                onClick={addTeammate}
                disabled={teammates.length >= 6}
                className="flex items-center gap-1 px-2 py-1 rounded text-xs bg-primary/20 text-primary hover:bg-primary/30 transition-colors disabled:opacity-50"
              >
                <Plus className="w-3 h-3" />
                Add
              </button>
            </div>

            <div className="space-y-3">
              {teammates.map((mate, index) => (
                <div
                  key={index}
                  className="p-3 rounded-lg border border-border bg-secondary/30 space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <User className="w-3.5 h-3.5" />
                      Teammate {index + 1}
                    </div>
                    {teammates.length > 1 && (
                      <button
                        onClick={() => removeTeammate(index)}
                        className="p-1 rounded hover:bg-red-500/20 text-muted-foreground hover:text-red-400 transition-colors"
                      >
                        <Minus className="w-3 h-3" />
                      </button>
                    )}
                  </div>

                  {/* Name */}
                  <input
                    type="text"
                    value={mate.name}
                    onChange={(e) => updateTeammate(index, { name: e.target.value })}
                    placeholder="Role name (e.g., researcher, tester)"
                    className="w-full px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                  />

                  {/* Model + Plan Mode */}
                  <div className="flex gap-2">
                    <select
                      value={mate.model}
                      onChange={(e) => updateTeammate(index, { model: e.target.value })}
                      className="flex-1 px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                    >
                      {MODEL_OPTIONS.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                    <button
                      onClick={() =>
                        updateTeammate(index, {
                          planModeRequired: !mate.planModeRequired,
                        })
                      }
                      className={`px-3 py-2 rounded-md text-xs border transition-colors ${
                        mate.planModeRequired
                          ? 'bg-primary/20 border-primary text-primary'
                          : 'bg-secondary border-border text-muted-foreground hover:text-foreground'
                      }`}
                      title="Require plan approval before implementation"
                    >
                      Plan
                    </button>
                  </div>

                  {/* Prompt */}
                  <textarea
                    value={mate.prompt}
                    onChange={(e) => updateTeammate(index, { prompt: e.target.value })}
                    placeholder="System prompt (optional)"
                    rows={2}
                    className="w-full px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none resize-none text-sm"
                  />
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 px-6 py-4 border-t border-border bg-secondary/30 flex-shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-sm hover:bg-secondary transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleCreate}
            disabled={!description.trim() || isCreating}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Play className="w-4 h-4" />
            {isCreating ? 'Creating...' : 'Create Team'}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreateTeamDialog;
