/**
 * CreateTeamDialog - Modal for creating a new Claude Agent Team.
 * Enhanced (Phase 12): template selector, per-teammate model dropdown,
 * "Save as Template" button, and star/favorite toggle.
 */
import { useState, useEffect } from 'react';
import { X, Users, Plus, Minus, Play, User, Star, Save, ChevronDown, Trash2 } from 'lucide-react';
import { useClaudeTeamsStore } from '../../stores/claude-teams-store';
import type { TeamTemplate } from '../../types/claude-teams';

interface TeammateConfig {
  name: string;
  prompt: string;
  model: string;
  planModeRequired: boolean;
}

const DEFAULT_TEAMMATE: TeammateConfig = {
  name: '',
  prompt: '',
  model: 'claude-sonnet-4-5-20250929',
  planModeRequired: false,
};

const MODEL_OPTIONS = [
  { value: 'claude-opus-4-6', label: 'Opus 4.6' },
  { value: 'claude-sonnet-4-5-20250929', label: 'Sonnet 4.5' },
  { value: 'claude-haiku-4-5-20251001', label: 'Haiku 4.5' },
];

interface CreateTeamDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CreateTeamDialog({ isOpen, onClose }: CreateTeamDialogProps) {
  const createTeam = useClaudeTeamsStore((s) => s.createTeam);
  const templates = useClaudeTeamsStore((s) => s.templates);
  const loadTemplates = useClaudeTeamsStore((s) => s.loadTemplates);
  const saveTemplate = useClaudeTeamsStore((s) => s.saveTemplate);
  const deleteTemplate = useClaudeTeamsStore((s) => s.deleteTemplate);
  const toggleTemplateFavorite = useClaudeTeamsStore((s) => s.toggleTemplateFavorite);

  const [description, setDescription] = useState('');
  const [teammates, setTeammates] = useState<TeammateConfig[]>([{ ...DEFAULT_TEAMMATE }]);
  const [isCreating, setIsCreating] = useState(false);
  const [showTemplateDropdown, setShowTemplateDropdown] = useState(false);
  const [showSaveTemplate, setShowSaveTemplate] = useState(false);
  const [templateName, setTemplateName] = useState('');
  const [templateDesc, setTemplateDesc] = useState('');
  const [isSavingTemplate, setIsSavingTemplate] = useState(false);

  // Load templates when dialog opens
  useEffect(() => {
    if (isOpen) {
      loadTemplates();
    }
  }, [isOpen, loadTemplates]);

  if (!isOpen) return null;

  const addTeammate = () => {
    if (teammates.length >= 6) return;
    setTeammates([...teammates, { ...DEFAULT_TEAMMATE }]);
  };

  const removeTeammate = (index: number) => {
    if (teammates.length <= 1) return;
    setTeammates(teammates.filter((_, i) => i !== index));
  };

  const updateTeammate = (index: number, updates: Partial<TeammateConfig>) => {
    setTeammates(
      teammates.map((t, i) => (i === index ? { ...t, ...updates } : t))
    );
  };

  const applyTemplate = (template: TeamTemplate) => {
    setTeammates(
      template.config.teammates.map((t) => ({
        name: t.name,
        prompt: t.prompt,
        model: t.model || 'claude-sonnet-4-5-20250929',
        planModeRequired: t.planModeRequired || false,
      }))
    );
    setShowTemplateDropdown(false);
  };

  const handleSaveTemplate = async () => {
    if (!templateName.trim()) return;
    setIsSavingTemplate(true);
    try {
      const validTeammates = teammates.filter((t) => t.name.trim());
      await saveTemplate({
        name: templateName.trim(),
        description: templateDesc.trim(),
        isFavorite: false,
        config: {
          teammates: validTeammates.map((t) => ({
            name: t.name.trim(),
            prompt: t.prompt.trim(),
            model: t.model,
            planModeRequired: t.planModeRequired || undefined,
          })),
        },
      });
      setTemplateName('');
      setTemplateDesc('');
      setShowSaveTemplate(false);
    } catch (err) {
      console.error('[CreateTeamDialog] save template error:', err);
    } finally {
      setIsSavingTemplate(false);
    }
  };

  const handleCreate = async () => {
    if (!description.trim()) return;

    setIsCreating(true);
    try {
      const success = await createTeam({
        name: '', // Name is auto-generated by Claude CLI
        description: description.trim(),
        teammates: teammates
          .filter((t) => t.name.trim() || t.prompt.trim())
          .map((t) => ({
            name: t.name.trim(),
            prompt: t.prompt.trim(),
            model: t.model,
            planModeRequired: t.planModeRequired,
          })),
      });

      if (success) {
        // Reset form
        setDescription('');
        setTeammates([{ ...DEFAULT_TEAMMATE }]);
        onClose();
      }
    } catch (err) {
      console.error('[CreateTeamDialog] create error:', err);
    } finally {
      setIsCreating(false);
    }
  };

  const hasValidTeammates = teammates.some((t) => t.name.trim());

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      {/* Dialog */}
      <div className="relative bg-card border border-border rounded-xl shadow-2xl w-full max-w-lg mx-4 max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border flex-shrink-0">
          <div className="flex items-center gap-3">
            <Users className="w-5 h-5 text-primary" />
            <h2 className="text-lg font-semibold">Create Team</h2>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-secondary transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 overflow-y-auto flex-1">
          {/* Template Selector */}
          <div className="relative">
            <label className="block text-sm font-medium text-muted-foreground mb-2">
              Start from Template
            </label>
            <button
              onClick={() => setShowTemplateDropdown(!showTemplateDropdown)}
              className="w-full flex items-center justify-between px-3 py-2 rounded-lg bg-secondary border border-border hover:border-primary/50 transition-colors text-sm"
            >
              <span className="text-muted-foreground">
                {templates.length > 0
                  ? `Choose a template (${templates.length} saved)`
                  : 'No saved templates'}
              </span>
              <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${showTemplateDropdown ? 'rotate-180' : ''}`} />
            </button>

            {/* Dropdown */}
            {showTemplateDropdown && templates.length > 0 && (
              <div className="absolute z-10 mt-1 w-full bg-card border border-border rounded-lg shadow-xl max-h-[200px] overflow-y-auto">
                {templates.map((tpl) => (
                  <div
                    key={tpl.id}
                    className="flex items-center gap-2 px-3 py-2 hover:bg-secondary cursor-pointer transition-colors group"
                  >
                    {/* Favorite toggle */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        toggleTemplateFavorite(tpl.id);
                      }}
                      className="shrink-0"
                      title={tpl.isFavorite ? 'Remove from favorites' : 'Add to favorites'}
                    >
                      <Star
                        className={`w-3.5 h-3.5 transition-colors ${
                          tpl.isFavorite
                            ? 'text-yellow-400 fill-yellow-400'
                            : 'text-muted-foreground hover:text-yellow-400'
                        }`}
                      />
                    </button>

                    {/* Template info (clickable to apply) */}
                    <div
                      className="flex-1 min-w-0"
                      onClick={() => applyTemplate(tpl)}
                    >
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-medium truncate">{tpl.name}</span>
                        <span className="text-[10px] text-muted-foreground shrink-0">
                          {tpl.config.teammates.length} teammate{tpl.config.teammates.length !== 1 ? 's' : ''}
                        </span>
                      </div>
                      {tpl.description && (
                        <p className="text-xs text-muted-foreground truncate">{tpl.description}</p>
                      )}
                    </div>

                    {/* Delete */}
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        deleteTemplate(tpl.id);
                      }}
                      className="shrink-0 opacity-0 group-hover:opacity-100 p-1 rounded hover:bg-red-500/20 text-muted-foreground hover:text-red-400 transition-all"
                      title="Delete template"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Task Description */}
          <div>
            <label className="block text-sm font-medium text-muted-foreground mb-2">
              Task Description
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="What should the team work on?"
              rows={3}
              className="w-full px-4 py-3 rounded-lg bg-secondary border border-border focus:border-primary focus:outline-none resize-none text-sm"
            />
          </div>

          {/* Teammates */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-sm font-medium text-muted-foreground">
                Teammates ({teammates.length}/6)
              </label>
              <button
                onClick={addTeammate}
                disabled={teammates.length >= 6}
                className="flex items-center gap-1 px-2 py-1 rounded text-xs bg-primary/20 text-primary hover:bg-primary/30 transition-colors disabled:opacity-50"
              >
                <Plus className="w-3 h-3" />
                Add
              </button>
            </div>

            <div className="space-y-3">
              {teammates.map((mate, index) => (
                <div
                  key={index}
                  className="p-3 rounded-lg border border-border bg-secondary/30 space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2 text-xs text-muted-foreground">
                      <User className="w-3.5 h-3.5" />
                      Teammate {index + 1}
                    </div>
                    {teammates.length > 1 && (
                      <button
                        onClick={() => removeTeammate(index)}
                        className="p-1 rounded hover:bg-red-500/20 text-muted-foreground hover:text-red-400 transition-colors"
                      >
                        <Minus className="w-3 h-3" />
                      </button>
                    )}
                  </div>

                  {/* Name */}
                  <input
                    type="text"
                    value={mate.name}
                    onChange={(e) => updateTeammate(index, { name: e.target.value })}
                    placeholder="Role name (e.g., researcher, tester)"
                    className="w-full px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                  />

                  {/* Model + Plan Mode */}
                  <div className="flex gap-2">
                    <select
                      value={mate.model}
                      onChange={(e) => updateTeammate(index, { model: e.target.value })}
                      className="flex-1 px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                    >
                      {MODEL_OPTIONS.map((opt) => (
                        <option key={opt.value} value={opt.value}>
                          {opt.label}
                        </option>
                      ))}
                    </select>
                    <button
                      onClick={() =>
                        updateTeammate(index, {
                          planModeRequired: !mate.planModeRequired,
                        })
                      }
                      className={`px-3 py-2 rounded-md text-xs border transition-colors ${
                        mate.planModeRequired
                          ? 'bg-primary/20 border-primary text-primary'
                          : 'bg-secondary border-border text-muted-foreground hover:text-foreground'
                      }`}
                      title="Require plan approval before implementation"
                    >
                      Plan
                    </button>
                  </div>

                  {/* Prompt */}
                  <textarea
                    value={mate.prompt}
                    onChange={(e) => updateTeammate(index, { prompt: e.target.value })}
                    placeholder="System prompt (optional)"
                    rows={2}
                    className="w-full px-3 py-2 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none resize-none text-sm"
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Save as Template (inline form, collapsible) */}
          {hasValidTeammates && (
            <div className="border border-border rounded-lg bg-secondary/20">
              {!showSaveTemplate ? (
                <button
                  onClick={() => setShowSaveTemplate(true)}
                  className="flex items-center gap-2 w-full px-3 py-2 text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  <Save className="w-3.5 h-3.5" />
                  Save current config as template
                </button>
              ) : (
                <div className="p-3 space-y-2">
                  <div className="flex items-center gap-2 text-xs text-muted-foreground mb-1">
                    <Save className="w-3.5 h-3.5" />
                    Save as Template
                  </div>
                  <input
                    type="text"
                    value={templateName}
                    onChange={(e) => setTemplateName(e.target.value)}
                    placeholder="Template name"
                    className="w-full px-3 py-1.5 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                    autoFocus
                  />
                  <input
                    type="text"
                    value={templateDesc}
                    onChange={(e) => setTemplateDesc(e.target.value)}
                    placeholder="Description (optional)"
                    className="w-full px-3 py-1.5 rounded-md bg-secondary border border-border focus:border-primary focus:outline-none text-sm"
                  />
                  <div className="flex items-center gap-2 justify-end">
                    <button
                      onClick={() => { setShowSaveTemplate(false); setTemplateName(''); setTemplateDesc(''); }}
                      className="px-2 py-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleSaveTemplate}
                      disabled={!templateName.trim() || isSavingTemplate}
                      className="flex items-center gap-1 px-3 py-1 rounded text-xs bg-primary/20 text-primary hover:bg-primary/30 transition-colors disabled:opacity-50"
                    >
                      <Save className="w-3 h-3" />
                      {isSavingTemplate ? 'Saving...' : 'Save'}
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-2 px-6 py-4 border-t border-border bg-secondary/30 flex-shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg text-sm hover:bg-secondary transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleCreate}
            disabled={!description.trim() || isCreating}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Play className="w-4 h-4" />
            {isCreating ? 'Creating...' : 'Create Team'}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreateTeamDialog;
